from sequana.viz.hist2d import Hist2D
from sequana.viz.boxplot import Boxplot
from sequana.viz.imshow import Imshow
from sequana.viz.scatter import ScatterHist
from sequana.viz.heatmap import Heatmap
from sequana.viz.corrplot import Corrplot
from sequana.viz.anova import ANOVA
from sequana.viz.volcano import Volcano
from sequana.viz.hinton import hinton
from sequana.viz.venn import plot_venn
from sequana.viz.pca import PCA
